export const expData = [
  {
    logo: "https://www.anahuac.mx/mexico/vinculacionempresarial/sites/default/files/2021-03/IUSA.jpg",
    name: "Auxiliar de Proyectos",
    enterprise: "INDUSTRIAS UNIDAS S.A. DE C.V.",
    journey: "Tiempo completo",
    startDate: "2020-09-01",
    endDate: "Actual",
    location: "Edo. Mex",
    modality: "Presencial",
    aptitudes: [
      "Trabajo en equipo",
      "Proactividad",
      "Comunicación",
      "Adaptabilidad",
      "Resolución de problemas",
    ],
  },
  {
    logo: "https://scontent.fmex11-4.fna.fbcdn.net/v/t39.30808-6/211569478_1195493050902168_4695177460703813923_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeESB0jDRd44TjJ4dgVLk0TakhSfPZnWQGaSFJ89mdZAZvlPvRSqWQQ2kLL2-zyIbmjangMAscKTKEs-4_5Y7QPZ&_nc_ohc=Xk1eO1QLUdoAb6ipVvq&_nc_zt=23&_nc_ht=scontent.fmex11-4.fna&oh=00_AfCMfw66ZJXzeDmLACHuAnE6U7NWL7TOm3olGFDeALvzrA&oe=6628D8B8",
    name: "Becario Desarrollador de Software Jr.",
    enterprise: "Oblekcomp Digicast",
    journey: "Tiempo completo",
    startDate: "2023-06-20",
    endDate: "Actual",
    location: "CDMX",
    modality: "En línea",
    aptitudes: [
      "Trabajo en equipo",
      "Proactividad",
      "Comunicación",
      "Adaptabilidad",
      "Resolución de problemas",
    ],
  },
  {
    logo: "https://www.anahuac.mx/mexico/vinculacionempresarial/sites/default/files/2021-03/IUSA.jpg",
    name: "Auxiliar de Proyectos",
    enterprise: "INDUSTRIAS UNIDAS S.A. DE C.V.",
    journey: "Tiempo completo",
    startDate: "2020-09-01",
    endDate: "Actual",
    location: "Edo. Mex",
    modality: "Presencial",
    aptitudes: [
      "Trabajo en equipo",
      "Proactividad",
      "Comunicación",
      "Adaptabilidad",
      "Resolución de problemas",
    ],
  },
  {
    logo: "https://scontent.fmex11-4.fna.fbcdn.net/v/t39.30808-6/211569478_1195493050902168_4695177460703813923_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeESB0jDRd44TjJ4dgVLk0TakhSfPZnWQGaSFJ89mdZAZvlPvRSqWQQ2kLL2-zyIbmjangMAscKTKEs-4_5Y7QPZ&_nc_ohc=Xk1eO1QLUdoAb6ipVvq&_nc_zt=23&_nc_ht=scontent.fmex11-4.fna&oh=00_AfCMfw66ZJXzeDmLACHuAnE6U7NWL7TOm3olGFDeALvzrA&oe=6628D8B8",
    name: "Becario Desarrollador de Software Jr.",
    enterprise: "Oblekcomp Digicast",
    journey: "Tiempo completo",
    startDate: "2023-06-20",
    endDate: "Actual",
    location: "CDMX",
    modality: "En línea",
    aptitudes: [
      "Trabajo en equipo",
      "Proactividad",
      "Comunicación",
      "Adaptabilidad",
      "Resolución de problemas",
    ],
  },
  {
    logo: "https://www.anahuac.mx/mexico/vinculacionempresarial/sites/default/files/2021-03/IUSA.jpg",
    name: "Auxiliar de Proyectos",
    enterprise: "INDUSTRIAS UNIDAS S.A. DE C.V.",
    journey: "Tiempo completo",
    startDate: "2020-09-01",
    endDate: "Actual",
    location: "Edo. Mex",
    modality: "Presencial",
    aptitudes: [
      "Trabajo en equipo",
      "Proactividad",
      "Comunicación",
      "Adaptabilidad",
      "Resolución de problemas",
    ],
  },
  {
    logo: "https://scontent.fmex11-4.fna.fbcdn.net/v/t39.30808-6/211569478_1195493050902168_4695177460703813923_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeESB0jDRd44TjJ4dgVLk0TakhSfPZnWQGaSFJ89mdZAZvlPvRSqWQQ2kLL2-zyIbmjangMAscKTKEs-4_5Y7QPZ&_nc_ohc=Xk1eO1QLUdoAb6ipVvq&_nc_zt=23&_nc_ht=scontent.fmex11-4.fna&oh=00_AfCMfw66ZJXzeDmLACHuAnE6U7NWL7TOm3olGFDeALvzrA&oe=6628D8B8",
    name: "Becario Desarrollador de Software Jr.",
    enterprise: "Oblekcomp Digicast",
    journey: "Tiempo completo",
    startDate: "2023-06-20",
    endDate: "Actual",
    location: "CDMX",
    modality: "En línea",
    aptitudes: [
      "Trabajo en equipo",
      "Proactividad",
      "Comunicación",
      "Adaptabilidad",
      "Resolución de problemas",
    ],
  },
];
